# 베이스 이미지
FROM node:20-alpine

# 작업 디렉토리 생성
WORKDIR /app

# 패키지 설치(캐시 활용)
COPY package.json pnpm-lock.yaml* yarn.lock* package-lock.json* ./
RUN if [ -f yarn.lock ]; then yarn install; \
    elif [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install; \
    else npm install; fi

# 전체 코드 복사 (단, node_modules는 제외됨)
COPY . .

# 개발용 포트 (예: 3000)
EXPOSE 3000

# 개발용 명령어: nodemon, ts-node-dev 등
CMD [ "npm", "run", "dev"]
