# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/6257233cbfa5c2b8e249dbe7

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/6257233cbfa5c2b8e249dbe7
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/6257233cbfa5c2b8e249dbe7
